import os
import pandas as pd
from typing import Dict, Any, List, Optional

from src.exports.dashboard_builder import HTMLDashboardBuilder
from src.exports.pdf_exporter import PrintablePDFExporter

class DataExporter:
    """
    Exports cleaned datasets (CSV, Excel), standalone reproducible Python analysis scripts,
    SQL query definitions, full Markdown reports, interactive HTML Executive Dashboards,
    and printable PDF/HTML executive briefing reports.
    """

    @classmethod
    def export_all(
        cls,
        output_dir: str,
        df_cleaned: pd.DataFrame,
        report_md: str,
        sql_queries: Dict[str, str],
        dataset_name: str = "dataset",
        metadata: Optional[Dict[str, Any]] = None,
        profiling: Optional[Dict[str, Any]] = None,
        kpi_results: Optional[Dict[str, Any]] = None,
        insights: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, str]:
        
        os.makedirs(output_dir, exist_ok=True)
        exported_paths = {}

        # 1. Cleaned CSV
        csv_path = os.path.join(output_dir, f"{dataset_name}_cleaned.csv")
        df_cleaned.to_csv(csv_path, index=False)
        exported_paths["cleaned_csv"] = csv_path

        # 2. Cleaned Excel
        excel_path = os.path.join(output_dir, f"{dataset_name}_cleaned.xlsx")
        try:
            df_cleaned.to_excel(excel_path, index=False)
            exported_paths["cleaned_excel"] = excel_path
        except Exception as e:
            print(f"Excel export skipped: {e}")

        # 3. Markdown Analysis Report
        report_path = os.path.join(output_dir, "analysis_report.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_md)
        exported_paths["markdown_report"] = report_path

        # 4. Standalone HTML Executive BI Dashboard
        if metadata and profiling:
            dash_path = os.path.join(output_dir, "executive_dashboard.html")
            HTMLDashboardBuilder.generate_html_dashboard(
                dataset_name=dataset_name,
                df_cleaned=df_cleaned,
                metadata=metadata,
                profiling=profiling,
                kpi_results=kpi_results or {},
                insights=insights or [],
                output_filepath=dash_path
            )
            exported_paths["executive_dashboard_html"] = dash_path

            # 5. Printable PDF / HTML Executive Briefing Report
            pdf_html_path = os.path.join(output_dir, "printable_executive_report.html")
            PrintablePDFExporter.generate_printable_report(
                dataset_name=dataset_name,
                metadata=metadata,
                profiling=profiling,
                report_md=report_md,
                output_filepath=pdf_html_path
            )
            exported_paths["printable_pdf_report"] = pdf_html_path

        # 4. SQL Queries file
        if sql_queries:
            sql_path = os.path.join(output_dir, "queries.sql")
            with open(sql_path, "w", encoding="utf-8") as f:
                f.write("-- Automated AI Data Analyst Recommended SQL Queries\n\n")
                for q_name, q_text in sql_queries.items():
                    f.write(f"-- Query: {q_name}\n")
                    f.write(q_text)
                    f.write("\n\n" + "="*50 + "\n\n")
            exported_paths["sql_queries"] = sql_path

        # 5. Reproducible Python Analysis Script
        py_script_path = os.path.join(output_dir, "reproducible_analysis.py")
        py_code = cls.generate_reproducible_python_script(csv_path)
        with open(py_script_path, "w", encoding="utf-8") as f:
            f.write(py_code)
        exported_paths["python_script"] = py_script_path

        return exported_paths

    @classmethod
    def generate_reproducible_python_script(cls, csv_filepath: str) -> str:
        return f"""# Reproducible Data Analysis Script
# Generated by AI Data Analyst Agent

import pandas as pd
import numpy as np

def run_analysis():
    print("Loading cleaned dataset from {csv_filepath}...")
    df = pd.read_csv(r"{csv_filepath}")
    
    print(f"Dataset Shape: {{df.shape[0]}} rows, {{df.shape[1]}} columns")
    print("\\nColumn Data Types:")
    print(df.dtypes)
    
    print("\\nDescriptive Statistics:")
    print(df.describe(include='all'))
    
    print("\\nCorrelation Matrix:")
    numeric_df = df.select_dtypes(include=[np.number])
    if not numeric_df.empty:
        print(numeric_df.corr())

if __name__ == "__main__":
    run_analysis()
"""
